name: Release
'on':
  push:
    tags:
      - '*'

defaults:
  run:
    working-directory: 'drkhsh.system_update'

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Check out the codebase.
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          path: 'drkhsh.system_update'

      - name: Set up Python 3.
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: '3.x'

      - name: Install Ansible.
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy.
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} drkhsh ansible-role-system-update
