---
- name: "Include Package Manager specific playbook"
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - 'include/{{ ansible_pkg_mgr }}.yml'
    - 'include/{{ ansible_distribution }}.yml'
    - 'include/{{ ansible_os_family }}.yml'
