---
- name: "Update & patch os"
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - 'include/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - 'include/{{ ansible_pkg_mgr }}.yml'
    - 'include/{{ ansible_distribution }}.yml'
    - 'include/{{ ansible_os_family }}.yml'
    - 'include/{{ ansible_os_family | replace("/", "_") | replace(" ", "_") }}.yml'
