---
- name: "Include Package Manager specific playbook"
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - '{{ ansible_pkg_mgr }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
