---
- name: "include | OpenBSD | Syspatch"
  when: ansible_distribution == "OpenBSD"
  become_method: community.general.doas
  community.general.syspatch:
  register: syspatch

- name: "include | OpenBSD | Update packages"
  when: ansible_distribution == "OpenBSD"
  become_method: community.general.doas
  community.general.openbsd_pkg:
    name: '*'
    state: latest
